---

- name: add vscode apt key
  ansible.builtin.command: rpm --import https://packages.microsoft.com/keys/microsoft.asc

- name: add vscode repo
  ansible.builtin.command: printf "[vscode]\nname=packages.microsoft.com\nbaseurl=https://packages.microsoft.com/yumrepos/vscode/\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc\nmetadata_expire=1h" | tee -a /etc/yum.repos.d/vscode.repo

- name: install latest visual studio code
  ansible.builtin.dnf:
    name: code

- name: install some popular vscode extensions
  ansible.builtin.command: code --install-extension {{ item }}
  with_items: "{{ vscode_extensions }}"
  become: yes
  become_user: "{{ local_username }}"

...
