---
- name: import microsoft gpg key
  ansible.builtin.rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  become: yes

- name: add vscode repository
  ansible.builtin.copy:
    dest: /etc/yum.repos.d/vscode.repo
    content: |
      [vscode]
      name=packages.microsoft.com
      baseurl=https://packages.microsoft.com/yumrepos/vscode/
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.microsoft.com/keys/microsoft.asc
      metadata_expire=1h
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: install latest visual studio code
  ansible.builtin.dnf:
    name: code
    state: present
  become: yes

- name: install some popular vscode extensions
  ansible.builtin.command: code --install-extension {{ item }}
  loop: "{{ vscode_extensions }}"
  become: yes
  become_user: "{{ local_username }}"
  changed_when: false

...
