---

laptop_mode: False             # True => this device is a laptop computer (enables TLP and power tools)
local_username: "{{ lookup('env', 'USER') }}"  # override at runtime: -e "local_username=$(id -un)"

...
