---

base_archiving_tools:
  - arj
  - cabextract
  - file-roller
  - sharutils
  - unace
  - unrar
  - unzip
  - uudeview
  - zip

base_productivity_tools:
  - libreoffice

base_system_tools:
  - fatrace
  - fdupes
  - gnome-calculator
  - progress
  - pwgen
  #- syncthing

base_system_tools_laptop:
#  - cpufrequtils
#  - powertop
  - tlp
  - tlp-rdw
  - acpi-call-dkms  # for newer ThinkPads (X220/T420 and later)
#  - tp-smapi-dkms  # for older ThinkPads

base_download_tools:
  - aria2
  - axel
  - transmission
  - speedtest-cli
  - wget
  - youtube-dl

base_developer_tools:
  - 2to3
  - ansible
  - ansible-lint
  - awscli
  - bat
  - bpython
  - black
  - cloc
  - clusterssh
  - colordiff
  - python-csvkit
  - curl
  - java-11-openjdk 
  - java-11-openjdk-devel
  - dos2unix
  - entr
  - exa
  - expect
  - filezilla
  - powerline 
  - powerline-fonts
  - fzf
  - g++
  - gedit-plugins
  - ghostwriter
  - git
  - git-extras
  - gitg
  - golang-go
  - htop
  - httpie
  - inotify-tools
  - ipython3
  - jq
  - makeself
  - meld
  - miller
  - moreutils
  - most
  - netcat
  - nmap
  - nmon
  - nodejs
  - pandoc
  - parallel
  - powerline
  - pssh
  #- puppet
  #- puppet-lint
  - pv
  - pylint
  - python3-demjson  # provides jsonlint-py3 for json lint
  - python3-jmespath
  - python3-pip
  - python3-poetry
  - ranger
  - rclone
  - recode
  - remmina
  - ripgrep  # launch using rg from the cli
  - ruby
  - shellcheck
  - siege
  - socat
  - sshfs
  - sshpass
  - sshuttle
  - tig
  - tilix
  - tree
  - uget
  - xclip
  - yamllint
  - zeal
  - tmux
  - tmux-powerline

base_developer_tools_pip3:
  - tldr

base_virtualization_tools:
  - dnf-plugins-core
  - docker-compose
  - docker-ce 
  - docker-ce-cli 
  - containerd.io 
  - docker-compose-plugin

base_media_tools:
  - ffmpeg
  - gimp
  - mediainfo
  - soundconverter
  - totem
#  - ubuntu-restricted-extras
  - vlc

base_permanent_night_light:
  night_light_enabled: False              # set this to True for permanently turning on night light
  night_light_schedule_automatic: False
  night_light_schedule_from: 0
  night_light_schedule_to: 24
  night_light_temperature: 4200

...
