---

# nerd fonts from https://github.com/ryanoasis/nerd-fonts/releases
# v3 restructured font paths; download zip archives from releases for reliability
terminal_customizations_nerd_fonts_version: "v3.2.1"

terminal_customizations_nerd_fonts:
  - FiraCode       # do not remove; tilix profile depends on FiraCode Nerd Font Mono
  - Inconsolata
  - SourceCodePro
  - UbuntuMono
  - Monoid
  - DroidSansMono
  - Hack
  - RobotoMono
  - VictorMono
  - CascadiaCode
  - NotoMono

...
