---

- name: install zsh and other related packages
  ansible.builtin.dnf:
    name: "{{ zsh_packages }}"
    state: present

- name: change user's shell to zsh
  ansible.builtin.user:
    name: "{{ local_username }}"
    shell: /bin/zsh

- name: install antigen
  ansible.builtin.git:
    dest: "~{{ local_username }}/.antigen"
    repo: "{{ zsh_antigen_url }}"
    version: "{{ zsh_antigen_git_version }}"
  become: yes
  become_user: "{{ local_username }}"

- block:
    - name: check if .zshrc exists in user's home dir
      ansible.builtin.stat:
        path: "~{{ local_username }}/.zshrc"
      register: dotzshrc

    - name: backup .zshrc if it exists
      ansible.builtin.copy:
        src: "~{{ local_username }}/.zshrc"
        dest: "~{{ local_username }}/.zshrc.orig"
      when: dotzshrc.stat.exists

    - name: copy the sample .zshrc file
      ansible.builtin.copy:
        src: .zshrc
        dest: "~{{ local_username }}/.zshrc"
        force: yes
  become: yes
  become_user: "{{ local_username }}"

...
